version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    cooldown:
      default-days: 7
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: '@eslint/*'
        update-types: ['version-update:semver-major']
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
      sanitize-html:
        patterns:
          - sanitize-html
          - '@types/sanitize-html'
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      typescript-eslint:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    cooldown:
      default-days: 7
    schedule:
      interval: 'daily'
