engineStrict: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - sharp

patchedDependencies:
  astro: patches/astro.patch

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - vite@6.4.1
