engineStrict: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

patchedDependencies:
  astro: patches/astro.patch

strictDepBuilds: true

strictPeerDependencies: true
